version: "3"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    expose:
      - "3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mdtype
      MYSQL_USER: mdadmin
      MYSQL_PASSWORD: root
  web:
    build: .
    command: python manage.py runserver 0:8000
    ports:
      - "8000:8000"
