# Generated by Django 4.1.3 on 2023-02-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('pronunciation', models.CharField(max_length=255)),
                ('meaning', models.CharField(max_length=255)),
            ],
        ),
    ]
