# Generated by Django 4.1.7 on 2023-03-21 14:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_mode', models.CharField(choices=[('meaning', 'Kiểm tra nghĩa'), ('spelling', 'Kiểm tra từ'), ('part_of_speech', 'Kiểm tra từ loại'), ('kanji', 'Kiểm tra hán nhật'), ('picture', 'Kiểm tra bằng hình ảnh')], default='meaning', max_length=20)),
                ('distractor_1', models.CharField(max_length=255, null=True)),
                ('distractor_2', models.CharField(max_length=255, null=True)),
                ('distractor_3', models.CharField(max_length=255, null=True)),
                ('distractor_4', models.CharField(max_length=255, null=True)),
                ('answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='topic_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('pronunciation', models.CharField(max_length=255)),
                ('meaning', models.CharField(max_length=255)),
                ('parts_of_speech', models.CharField(choices=[(None, 'Select parts of speech'), ('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('interjection', 'Interjection')], default=None, max_length=20, null=True)),
                ('attempts_correct', models.BigIntegerField(default=0)),
                ('attempts_incorrect', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None)),
                ('attempts_total', models.BigIntegerField(default=0)),
                ('checks_correct', models.BigIntegerField(default=0)),
                ('checks_incorrect', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None)),
                ('checks_total', models.BigIntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('examples', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None)),
                ('synonyms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None)),
                ('antonyms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None)),
                ('flag', models.BooleanField(default=True)),
                ('uncheck_ifnull', models.BooleanField(default=False)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to='collection.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='collection.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='collection.vocabulary'),
        ),
    ]
