# Generated by Django 4.1.7 on 2023-03-19 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_alter_vocabulary_antonyms_alter_vocabulary_examples_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabulary',
            old_name='correct',
            new_name='attempts_correct',
        ),
        migrations.RenameField(
            model_name='vocabulary',
            old_name='incorrect',
            new_name='attempts_incorrect',
        ),
        migrations.RenameField(
            model_name='vocabulary',
            old_name='total',
            new_name='attempts_total',
        ),
    ]
