# Generated by Django 4.1.7 on 2023-03-19 10:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_rename_correct_vocabulary_attempts_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='check_correct',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='check_incorrect',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='check_total',
            field=models.BigIntegerField(default=0),
        ),
    ]
