# Generated by Django 4.1.7 on 2023-03-19 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_vocabulary_check_correct_vocabulary_check_incorrect_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabulary',
            old_name='check_correct',
            new_name='checks_correct',
        ),
        migrations.RenameField(
            model_name='vocabulary',
            old_name='check_incorrect',
            new_name='checks_incorrect',
        ),
        migrations.RenameField(
            model_name='vocabulary',
            old_name='check_total',
            new_name='checks_total',
        ),
    ]
